version: 2.1

orbs:
  python: circleci/python@1.5
  node: circleci/node@4.8.1
  browser-tools: circleci/browser-tools@1.4.6

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - node/install-packages:
          pkg-manager: yarn
          app-dir: web
      - run:
          name: "Yarn build"
          command: cd web && yarn build
      - run:
          name: Run tests
          command: cd server && pytest

workflows:
  build-and-test:
    jobs:
      - build-and-test
